version: "3.9"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile.production
    image:  strangeman/devops-for-programmers-project-lvl1:latest
    command: npm test
    env_file: .env.example
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

  db:
    image: postgres:14
    env_file: .env.example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5